version: "3"

services:
  sorusora:
    image: ghcr.io/seoulsky/sorusora:latest
    container_name: sorusora
    volumes:
      - ./sorusora/logs:/app/logs
      - ./sorusora/cache:/app/cache
      - ./sorusora/cache/algos_packages:${HOME}/.local/share/argos-translate/packages/
      - ./sorusora/cache/algos_cache:${HOME}/.local/cache/argos-translate/
    env_file:
      - .env
    restart: always
    environment:
      - CHAT_AI_HOST=sorusora-ai

  sorusora-ai:
    image: ghcr.io/seoulsky/sorusora-ai:latest
    container_name: sorusora-ai
    env_file:
      - .env
    restart: always
    ports:
      - "50051:50051"

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongoDB:/data/db
    restart: always
