version: "3"

services:
  sorusora:
    build:
      context: .
      dockerfile: sorusora/Dockerfile
    container_name: sorusora
    volumes:
      - ./sorusora/logs:/app/logs
      - ./sorusora/cache:/app/cache
      - ./sorusora/cache/algos_packages:${HOME}/.local/share/argos-translate/packages/
      - ./sorusora/cache/algos_cache:${HOME}/.local/cache/argos-translate/
    env_file:
      - .env

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongoDB:/data/db
