version: "3"

services:
  sorusora:
    build: .
    container_name: sorusora
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
    env_file:
      - .env

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    volumes:
      - ~/mongo:/data/db
