name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  PROTO_BUILD_SCRIPT: build-protos.sh

jobs:
  sorusora:
    runs-on: ubuntu-latest
    steps:
      - name: Build sorusora
        uses: ./.github/workflows/build-push
        with:
          context: sorusora

  sorusora-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Build sorusora-ai
        uses: ./.github/workflows/build-push
        with:
          context: sorusora-ai
