name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"

env:
  USERNAME: ${{ github.repository_owner }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sorusora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build sorusora
        uses: ./.github/workflows/build-push
        with:
          context: sorusora
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

  sorusora-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build sorusora-ai
        uses: ./.github/workflows/build-push
        with:
          context: sorusora-ai
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
