name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io

jobs:
  sorusora:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the build environment
        uses: ./.github/workflows/build-setup

      - name: Get Repository Name in Lowercase
        id: repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.lowercase }}

      - name: Build and push sorusora
        uses: docker/build-push-action@v4
        with:
          context: ./sorusora
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  sorusora-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the build environment
        uses: ./.github/workflows/build-setup

      - name: Get Repository Name in Lowercase
        id: repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.lowercase }}-ai

      - name: Build and push sorusora-ai
        uses: docker/build-push-action@v4
        with:
          context: ./sorusora-ai
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
