name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  PROTO_BUILD_SCRIPT: build-protos.sh

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.repo-name.outputs.lowercase }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Proto files
        run: |
          chmod +x ${{ env.PROTO_BUILD_SCRIPT }} && ./${{ env.PROTO_BUILD_SCRIPT }}

      - name: Get Repository Name in Lowercase
        id: repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

  sorusora:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.setup.outputs.repo-name }}

      - name: Build and push sorusora
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:sorusora"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  sorusora-ai:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.setup.outputs.repo-name }}-ai

      - name: Build and push sorusora-ai
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:sorusora-ai"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
