name: Pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_SCRIPT: build-protos.sh
  PYLINT_SCRIPT: scripts/pylint.sh

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      ROOT_PATH: sorusora
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $ROOT_PATH/requirements.txt

      - name: Analysing the code with pylint
        run: |
          cd $ROOT_PATH
          chmod +x ${{ env.BUILD_SCRIPT }}
          ./${{ env.BUILD_SCRIPT }}
          chmod +x ${{ env.PYLINT_SCRIPT }}
          ./${{ env.PYLINT_SCRIPT }}
